version: '3.5'

services:
  web:
    container_name: assessme
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'
  #   command: ['npm','run', 'test']
